name: pop-prod
channels:
  - conda-forge
dependencies:
  - python=3.10
  - uvicorn=0.23.2
  - fastapi=0.101.0
  - pydantic=2.1.1
  - pip
  - pip:
      - pandas
      - scipy
      - numpy
      - scikit-learn
      - seaborn
      - typing_extensions
      - xgboost